version: '3'
services:
  database:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=productdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
  merge_catalog_service:
    image: mergecatalog:latest
    container_name: mergecatalog
    ports:
      - 8080:8080
    volumes:
    - csv-data: var/csvdata
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/productdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    depends_on:
      - database
volumes:
  csv-data